# Generated by Django 5.2 on 2026-04-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0002_entry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
    ]
